version: "3"
services:
  newfrontend:
    restart: always
    build: ./newfrontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./newfrontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    restart: always
    build: ./api
    ports:
      - "5051:5051"
    volumes:
      - ./api:/app

