version: "3"
services:
  newfrontend:
    restart: always
    build: ./newfrontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./newfrontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    restart: always
    build: ./api
    ports:
      - "5051:5051"
    volumes:
      - ./api:/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongodb_data:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword
      ME_CONFIG_MONGODB_URL: mongodb://root:mypassword@mongo:27017/
    depends_on:
     - mongo
volumes:
  mongodb_data:

